/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    ChatInterface: typeof import('./src/components/consumer/ChatInterface.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    ConversationList: typeof import('./src/components/consumer/ConversationList.vue')['default']
    DocumentViewer: typeof import('./src/components/consumer/DocumentViewer.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ErrorBoundary: typeof import('./src/components/ErrorBoundary.vue')['default']
    KnowledgeBaseManager: typeof import('./src/components/admin/KnowledgeBaseManager.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    MessageBubble: typeof import('./src/components/consumer/MessageBubble.vue')['default']
    PermissionMatrix: typeof import('./src/components/admin/PermissionMatrix.vue')['default']
    RoleSelector: typeof import('./src/components/admin/RoleSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemStats: typeof import('./src/components/admin/SystemStats.vue')['default']
    UserTable: typeof import('./src/components/admin/UserTable.vue')['default']
    VirtualScroll: typeof import('./src/components/shared/VirtualScroll.vue')['default']
    WritingAssistant: typeof import('./src/components/consumer/WritingAssistant.vue')['default']
  }
}
